package com.anurag.Learning_REST_APIs.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "students")
public class Student
{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private Integer age;

    @Column(nullable = false)
    private String course;

    public Student()
    {

    }

    public Student(String name, String email, Integer age, String course)
    {
        this.name = name;
        this.email = email;
        this.age = age;
        this.course = course;
    }

    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public Integer getAge()
    {
        return age;
    }

    public void setAge(Integer age)
    {
        this.age = age;
    }

    public String getCourse()
    {
        return course;
    }

    public void setCourse(String course)
    {
        this.course = course;
    }
}

/*
 * ==========================================================
 *                    ENTITY SUMMARY
 * ==========================================================
 *
 * Entity Name  : Student
 * Database     : studentdb
 * Table Name   : students
 *
 * ----------------------------------------------------------
 * Database Table Structure
 * ----------------------------------------------------------
 * | id | name | email | age | course |
 * ----------------------------------------------------------
 *
 * id
 * ----
 * -> Primary Key
 * -> Auto Generated by PostgreSQL
 *
 * name
 * -----
 * -> Cannot be NULL
 *
 * email
 * ------
 * -> Cannot be NULL
 * -> Must be UNIQUE
 *
 * age
 * ----
 * -> Cannot be NULL
 *
 * course
 * -------
 * -> Cannot be NULL
 *
 * ----------------------------------------------------------
 * Annotations Used
 * ----------------------------------------------------------
 * @Entity
 *      Marks this class as a JPA Entity.
 *
 * @Table(name = "students")
 *      Maps this entity to the "students" table.
 *
 * @Id
 *      Declares the Primary Key.
 *
 * @GeneratedValue(strategy = GenerationType.IDENTITY)
 *      Database automatically generates the ID.
 *
 * @Column(nullable = false)
 *      Column cannot contain NULL values.
 *
 * @Column(unique = true)
 *      Duplicate values are not allowed.
 *
 * ==========================================================
 * This entity will be used by:
 *
 * Controller
 *      ↓
 * Service
 *      ↓
 * Repository
 *      ↓
 * PostgreSQL Database
 * ==========================================================
 */